"""This script will print a list of files generated by the  AGTS scripts
that run every weekend.

Just do::
    
    $ python check_images
"""

import os

from gpaw.test.big.agts import AGTSQueue

queue = AGTSQueue()
queue.collect()

for job in queue.jobs:
    if not job.creates:
        continue
    for name in job.creates:
        path = os.path.join(job.dir, name)
        print(path)
